<?php
/** @package Clinicacmo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MedicoMap.php");

/**
 * MedicoDAO provides object-oriented access to the medicos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Clinicacmo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MedicoDAO extends Phreezable
{
	/** @var int */
	public $Idmedicos;

	/** @var string */
	public $NmMedico;

	/** @var int */
	public $CpfMedico;

	/** @var int */
	public $RgMedico;

	/** @var int */
	public $NrCrm;

	/** @var string */
	public $NmUsuario;

	/** @var string */
	public $Senha;

	/** @var int */
	public $NumAcesso;

	/** @var int */
	public $LaudoIdlaudo;

	/** @var int */
	public $CdEspecialidade;



}
?>